#!/usr/bin/env python3
"""Deterministic checks for triage's untrusted-verification contract."""

from __future__ import annotations

import hashlib
import json
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TRIAGE = (ROOT / "skills/engineering/triage/SKILL.md").read_text()
SAFE_VERIFICATION = (
    ROOT / "skills/engineering/triage/SAFE-VERIFICATION.md"
).read_text()
FIXTURE = json.loads(
    (ROOT / "tests/fixtures/triage-safety.json").read_text()
)

AI_PREFIX = "> *This was generated by AI during triage.*"

REQUIRED_ISOLATION_GUARANTEES = {
    "process_tree_confined",
    "credentials_inaccessible",
    "ssh_agent_inaccessible",
    "private_host_files_inaccessible",
    "original_workspace_inaccessible",
    "git_metadata_disjoint",
    "minimal_clean_environment",
    "network_default_denied",
    "output_boundary",
    "resource_bounds",
    "cleanup_confirmed",
}
ATTEMPT_GUARANTEES = {
    "authentication_environment": {
        "credentials_inaccessible",
        "minimal_clean_environment",
    },
    "ssh_agent": {"ssh_agent_inaccessible"},
    "private_home_file": {"private_host_files_inaccessible"},
    "original_worktree": {"original_workspace_inaccessible"},
    "shared_git_metadata": {"git_metadata_disjoint"},
    "network": {"network_default_denied"},
    "prompt_like_or_sensitive_output": {"output_boundary"},
}


def expect(condition: bool, message: str) -> None:
    if not condition:
        print(f"error: {message}", file=sys.stderr)
        raise SystemExit(1)


def check_normal_flow_order() -> None:
    verification = TRIAGE.index("2. **Verify safely.")
    grilling = TRIAGE.index("3. **Grill when required.")
    approval = TRIAGE.index("4. **Present the final recommendation for approval.")
    mutation = TRIAGE.index("5. **Apply the evidence-current approved outcome.")
    expect(
        verification < grilling < approval < mutation,
        "normal triage does not verify and grill before final approval and mutation",
    )


def check_isolation_decisions() -> None:
    for profile in FIXTURE["isolation_profiles"]:
        guarantees = profile["guarantees"]
        missing = REQUIRED_ISOLATION_GUARANTEES - {
            name for name, established in guarantees.items() if established
        }
        if profile["network_required"]:
            network_confined = guarantees.get("network_enabled_through_boundary", False)
        else:
            network_confined = guarantees.get("network_default_denied", False)
        decision = "execute" if not missing and network_confined else "blocked"
        expect(
            decision == profile["expected_decision"],
            f"wrong isolation decision for {profile['id']}: {decision}",
        )

    ordinary_worktree = next(
        profile for profile in FIXTURE["isolation_profiles"]
        if profile["id"] == "ordinary-disposable-worktree"
    )
    expect(
        ordinary_worktree["expected_decision"] == "blocked",
        "ordinary disposable worktree was treated as an execution sandbox",
    )


def check_malicious_fixture_matrix() -> None:
    expect(
        "repository scripts and dependencies encountered during external-request verification"
        in TRIAGE,
        "triage trusts unchanged repository scripts or dependencies during external verification",
    )
    expect(
        "repository script or dependency while verifying an external request"
        in SAFE_VERIFICATION,
        "safe-verification narrows protection to contributor-supplied scripts or dependencies",
    )
    expected_attempts = {
        "authentication_environment",
        "ssh_agent",
        "private_home_file",
        "original_worktree",
        "shared_git_metadata",
        "network",
        "prompt_like_or_sensitive_output",
    }
    scenarios = FIXTURE["malicious_scenarios"]
    expect(
        {scenario["attempt"] for scenario in scenarios} == expected_attempts,
        "malicious fixture matrix does not cover every required capability",
    )
    expect(
        {scenario["origin"] for scenario in scenarios}
        == {"external-pr", "reporter-reproduction"},
        "malicious fixture matrix does not cover PR and reproduction origins",
    )
    proven_profile = next(
        profile for profile in FIXTURE["isolation_profiles"]
        if profile["id"] == "proven-boundary-network-denied"
    )
    for scenario in scenarios:
        expect(
            set(scenario)
            == {"id", "origin", "attempt", "synthetic_marker", "expected_result"},
            f"malicious fixture {scenario['id']} contains executable or unexpected material",
        )
        expect(
            scenario["synthetic_marker"].startswith("SYNTHETIC_FIXTURE_"),
            f"malicious fixture {scenario['id']} is not clearly synthetic",
        )
        required = ATTEMPT_GUARANTEES[scenario["attempt"]]
        confined = all(proven_profile["guarantees"][name] for name in required)
        result = (
            "captured-outside-model"
            if scenario["attempt"] == "prompt_like_or_sensitive_output" and confined
            else "denied" if confined
            else "exposed"
        )
        expect(
            result == scenario["expected_result"],
            f"malicious fixture {scenario['id']} can expose its attempted capability",
        )

    for phrase in (
        "entire process tree",
        "SSH or GPG agent sockets",
        "private home files",
        "original tracked files, untracked files, index",
        "refs, config, hooks, objects",
        "deny network by default",
        "where the model and public surfaces cannot read them",
    ):
        expect(phrase in SAFE_VERIFICATION, f"safe-verification contract omits {phrase!r}")


def check_bounded_sanitized_output() -> None:
    output = FIXTURE["untrusted_output"]
    raw = "\n".join(output["raw_chunks"]).encode()
    expect(
        len(raw) > output["max_capture_bytes"],
        "output fixture does not exercise its byte bound",
    )

    # This models the trusted boundary: raw bytes are bounded and never become
    # the return value. Triage receives only the fixture's reduced result.
    captured = raw[: output["max_capture_bytes"]]
    expect(len(captured) == output["max_capture_bytes"], "raw output was not bounded")
    released = output["sanitized_result"]
    note = (
        f"{AI_PREFIX}\n\n## Verification\n\n"
        f"**Status:** {released['status']}\n"
        f"**Exercised path:** {released['exercised_path']}\n"
        f"**Observed result:** {released['observed_result']}\n"
        f"**Blocked capabilities:** {', '.join(released['blocked_capabilities'])}\n"
    )
    expect(note.startswith(AI_PREFIX), "durable verification note lost the AI prefix")
    for marker in output["prohibited_markers"]:
        expect(marker not in note, f"untrusted output marker reached durable note: {marker}")
    for prohibited in (
        "use the model itself as the sanitizer",
        "credential locations",
        "vault or secret identifiers",
        "private host paths",
        "prompt-like instructions",
    ):
        expect(prohibited in SAFE_VERIFICATION, f"output contract omits {prohibited!r}")


def snapshot_tree(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def check_workspace_and_git_preservation() -> None:
    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        original = root / "original"
        for relative in FIXTURE["preservation_paths"]:
            path = original / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(f"SYNTHETIC_FIXTURE_STATE:{relative}\n")
        before = snapshot_tree(original)

        disposable_parent = root / "isolated-run"
        disposable_source = disposable_parent / "source"
        disposable_source.mkdir(parents=True)
        for scenario in FIXTURE["malicious_scenarios"]:
            (disposable_source / f"{scenario['id']}.attempt").write_text(
                f"denied:{scenario['attempt']}\n"
            )
        expect(
            snapshot_tree(original) == before,
            "synthetic external request changed original repository state",
        )

        for path in sorted(
            disposable_parent.rglob("*"),
            key=lambda candidate: len(candidate.parts),
            reverse=True,
        ):
            if path.is_file():
                path.unlink()
            else:
                path.rmdir()
        disposable_parent.rmdir()
        expect(not disposable_parent.exists(), "disposable source or state survived cleanup")

    expected_paths = {
        "tracked-file",
        "untracked-file",
        ".git/index",
        ".git/refs/heads/main",
        ".git/config",
        ".git/hooks/pre-commit",
        ".git/objects/aa/synthetic-object",
    }
    expect(
        set(FIXTURE["preservation_paths"]) == expected_paths,
        "preservation fixture omits repository state",
    )


def snapshot_key(snapshot: dict[str, object]) -> str:
    return json.dumps(snapshot, sort_keys=True, separators=(",", ":"))


def check_approval_and_override_dry_runs() -> None:
    for case in FIXTURE["approval_dry_runs"]:
        tracker_state = {"labels": [], "comments": [], "closed": False}
        if case["quick_override"]:
            may_mutate = case["category_present"] and case["plan_listed"]
            external_execution_authorized = False
        else:
            may_mutate = (
                case["verification_complete"]
                and case["required_decisions_resolved"]
                and snapshot_key(case["approved_snapshot"])
                == snapshot_key(case["current_snapshot"])
            )
            external_execution_authorized = case["safe_execution_established"]

        if may_mutate:
            plan = case["current_snapshot"]["mutation_plan"]
            tracker_state["labels"] = plan["labels"]
            tracker_state["comments"] = plan["comments"]
            tracker_state["closed"] = plan["closed"]

        expect(
            may_mutate == case["expected_mutation"],
            f"wrong approval result for {case['id']}",
        )
        expect(
            external_execution_authorized == case["expected_external_execution"],
            f"quick override or isolation decision authorized unsafe execution for {case['id']}",
        )
        if not may_mutate:
            expect(
                tracker_state == {"labels": [], "comments": [], "closed": False},
                f"unapproved dry run mutated tracker state for {case['id']}",
            )
        for comment in tracker_state["comments"]:
            expect(
                comment.startswith(AI_PREFIX),
                f"dry-run comment lost AI prefix for {case['id']}",
            )

    case_results = {
        case["id"]: case["expected_mutation"]
        for case in FIXTURE["approval_dry_runs"]
    }
    expect(case_results["final-approval"], "final approval cannot apply its current outcome")
    expect(not case_results["changed-evidence"], "changed evidence reused stale approval")
    expect(case_results["renewed-evidence-approval"], "renewed evidence approval cannot mutate")
    expect(not case_results["changed-recommendation"], "changed recommendation reused stale approval")
    expect(
        case_results["renewed-recommendation-approval"],
        "renewed recommendation approval cannot mutate",
    )
    expect(case_results["quick-override"], "explicit quick override was not preserved")

    expect(
        "without normal verification or grilling" in TRIAGE,
        "quick override does not document its normal-flow bypass",
    )
    expect(
        "A quick override never authorizes execution of external material" in TRIAGE,
        "quick override can authorize unsafe external execution",
    )


def main() -> None:
    check_normal_flow_order()
    check_isolation_decisions()
    check_malicious_fixture_matrix()
    check_bounded_sanitized_output()
    check_workspace_and_git_preservation()
    check_approval_and_override_dry_runs()
    print("triage safety tests ok")


if __name__ == "__main__":
    main()
