#!/usr/bin/env python3
"""Deterministic dry-run checks for triage's untrusted-verification contract."""

from __future__ import annotations

import hashlib
import json
import shutil
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
TRIAGE = (ROOT / "skills/engineering/triage/SKILL.md").read_text()
SAFE_VERIFICATION = (
    ROOT / "skills/engineering/triage/SAFE-VERIFICATION.md"
).read_text()
FIXTURE = json.loads(
    (ROOT / "tests/fixtures/triage-safety.json").read_text()
)

AI_PREFIX = "> *This was generated by AI during triage.*"
REQUIRED_ISOLATION_GUARANTEES = {
    "process_tree_confined",
    "credentials_inaccessible",
    "ssh_agent_inaccessible",
    "private_host_files_inaccessible",
    "original_workspace_inaccessible",
    "git_metadata_disjoint",
    "minimal_clean_environment",
    "network_default_denied",
    "output_boundary",
    "resource_bounds",
    "cleanup_confirmed",
}
EXPECTED_ATTEMPTS = {
    "authentication_environment",
    "ssh_agent",
    "private_home_file",
    "original_worktree",
    "shared_git_metadata",
    "network",
    "prompt_like_or_sensitive_output",
}


def expect(condition: bool, message: str) -> None:
    if not condition:
        print(f"error: {message}", file=sys.stderr)
        raise SystemExit(1)


def snapshot_tree(root: Path) -> dict[str, str]:
    return {
        path.relative_to(root).as_posix(): hashlib.sha256(path.read_bytes()).hexdigest()
        for path in sorted(root.rglob("*"))
        if path.is_file()
    }


def seed_original(root: Path) -> None:
    for relative in FIXTURE["preservation_paths"]:
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"SYNTHETIC_FIXTURE_STATE:{relative}\n")
    for relative, value in (
        ("private-home/fixture-private-file", "SYNTHETIC_FIXTURE_HOME_FILE"),
        ("agent/fixture-agent.sock", "SYNTHETIC_FIXTURE_AGENT_SOCKET"),
    ):
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(f"{value}\n")


class SyntheticBoundary:
    """A non-executing fixture model for trusted policy dry runs.

    It never runs tracker material or probes host resources. Access attempts are
    resolved only against synthetic paths under a temporary directory.
    """

    def __init__(self, run_root: Path, original: Path, weakened: str | None = None):
        self.root = run_root
        self.original = original
        self.home = run_root / "home"
        self.source = run_root / "source"
        self.git_common_dir = self.source / ".git"
        self.capture_file = run_root / "private-output" / "raw"
        for path in (self.home, self.git_common_dir / "refs/heads"):
            path.mkdir(parents=True, exist_ok=True)

        self.environment = {
            "HOME": str(self.home),
            "PATH": "/synthetic-fixture/bin",
            "GIT_CONFIG_GLOBAL": str(run_root / "config/gitconfig"),
        }
        self.allowed_roots = [run_root]
        self.network_allowed = False
        self.output_boundary = True

        if weakened == "authentication_environment":
            self.environment["FIXTURE_AUTH_TOKEN"] = "SYNTHETIC_FIXTURE_AUTH_ENV"
        elif weakened == "ssh_agent":
            self.environment["SSH_AUTH_SOCK"] = str(
                original / "agent/fixture-agent.sock"
            )
            self.allowed_roots.append(original)
        elif weakened in {
            "private_home_file",
            "original_worktree",
            "shared_git_metadata",
        }:
            self.allowed_roots.append(original)
            if weakened == "shared_git_metadata":
                self.git_common_dir = original / ".git"
        elif weakened == "network":
            self.network_allowed = True
        elif weakened == "prompt_like_or_sensitive_output":
            self.output_boundary = False

    def can_access(self, candidate: Path) -> bool:
        resolved = candidate.resolve()
        return any(
            resolved.is_relative_to(root.resolve()) for root in self.allowed_roots
        )

    def capture(self, raw: str) -> str:
        if not self.output_boundary:
            return "model-visible"
        self.capture_file.parent.mkdir(parents=True, exist_ok=True)
        self.capture_file.write_text(raw)
        return "captured-outside-model"

    def cleanup(self) -> None:
        shutil.rmtree(self.root)


def attempt_once(boundary: SyntheticBoundary, scenario: dict[str, object]) -> str:
    attempt = str(scenario["attempt"])
    marker = str(scenario["synthetic_marker"])
    if attempt == "authentication_environment":
        return (
            "exposed"
            if marker in boundary.environment.values()
            else "denied"
        )
    if attempt == "ssh_agent":
        socket = boundary.environment.get("SSH_AUTH_SOCK")
        return (
            "exposed"
            if socket is not None and boundary.can_access(Path(socket))
            else "denied"
        )
    if attempt == "private_home_file":
        target = boundary.original / "private-home/fixture-private-file"
        return "exposed" if boundary.can_access(target) else "denied"
    if attempt == "original_worktree":
        target = boundary.original / "tracked-file"
        return "exposed" if boundary.can_access(target) else "denied"
    if attempt == "shared_git_metadata":
        # A protected run may write only its standalone synthetic Git state.
        if boundary.git_common_dir != boundary.original / ".git":
            standalone_ref = boundary.git_common_dir / "refs/heads/fixture"
            standalone_ref.write_text(marker)
        shared_ref = boundary.original / ".git/refs/heads/main"
        return "exposed" if boundary.can_access(shared_ref) else "denied"
    if attempt == "network":
        return "exposed" if boundary.network_allowed else "denied"
    if attempt == "prompt_like_or_sensitive_output":
        return boundary.capture(marker)
    raise AssertionError(f"unknown synthetic attempt: {attempt}")


def attempt_through_descendants(
    boundary: SyntheticBoundary, scenario: dict[str, object]
) -> list[str]:
    """Apply one boundary recursively to model child and grandchild attempts."""

    results: list[str] = []

    def visit(depth: int) -> None:
        results.append(attempt_once(boundary, scenario))
        if depth > 0:
            visit(depth - 1)

    visit(int(scenario["descendant_depth"]))
    return results


def check_normal_flow_order_and_text() -> None:
    verification = TRIAGE.index("2. **Verify safely.")
    grilling = TRIAGE.index("3. **Grill when required.")
    approval = TRIAGE.index("4. **Present the final recommendation for approval.")
    mutation = TRIAGE.index("5. **Apply the evidence-current approved outcome.")
    expect(
        verification < grilling < approval < mutation,
        "normal triage does not verify and grill before final approval and mutation",
    )
    expect(
        "Wait for explicit maintainer approval of this evidence-and-recommendation snapshot."
        in TRIAGE,
        "normal flow can mutate without explicit maintainer approval",
    )
    expect(AI_PREFIX in TRIAGE, "triage lost the standard AI prefix")
    expect(
        "repository scripts and dependencies encountered during external-request verification"
        in TRIAGE,
        "triage trusts unchanged repository scripts or dependencies during external verification",
    )
    expect(
        "repository script or dependency while verifying an external request"
        in SAFE_VERIFICATION,
        "safe-verification narrows protection to contributor-supplied scripts or dependencies",
    )


def check_isolation_decisions() -> None:
    for profile in FIXTURE["isolation_profiles"]:
        guarantees = profile["guarantees"]
        established = {
            name for name, available in guarantees.items() if available
        }
        missing = REQUIRED_ISOLATION_GUARANTEES - established
        network_confined = (
            guarantees.get("network_enabled_through_boundary", False)
            if profile["network_required"]
            else guarantees.get("network_default_denied", False)
        )
        decision = "execute" if not missing and network_confined else "blocked"
        expect(
            decision == profile["expected_decision"],
            f"wrong isolation decision for {profile['id']}: {decision}",
        )

    ordinary = next(
        profile
        for profile in FIXTURE["isolation_profiles"]
        if profile["id"] == "ordinary-disposable-worktree"
    )
    expect(
        ordinary["expected_decision"] == "blocked",
        "ordinary disposable worktree was treated as an execution sandbox",
    )


def check_malicious_fixture_attempts_and_preservation() -> None:
    scenarios = FIXTURE["malicious_scenarios"]
    expect(
        {scenario["attempt"] for scenario in scenarios} == EXPECTED_ATTEMPTS,
        "malicious fixture matrix does not cover every required capability",
    )
    expect(
        {scenario["origin"] for scenario in scenarios}
        == {"external-pr", "reporter-reproduction"},
        "malicious fixture matrix does not cover PR and reproduction origins",
    )

    with tempfile.TemporaryDirectory() as temporary:
        root = Path(temporary)
        original = root / "original"
        seed_original(original)
        original_before = snapshot_tree(original)

        for scenario in scenarios:
            expect(
                set(scenario)
                == {
                    "id",
                    "origin",
                    "attempt",
                    "descendant_depth",
                    "synthetic_marker",
                    "expected_protected",
                    "expected_weakened",
                },
                f"malicious fixture {scenario['id']} contains executable material",
            )
            expect(
                str(scenario["synthetic_marker"]).startswith("SYNTHETIC_FIXTURE_"),
                f"malicious fixture {scenario['id']} is not clearly synthetic",
            )

            protected = SyntheticBoundary(
                root / f"protected-{scenario['id']}", original
            )
            protected_results = attempt_through_descendants(protected, scenario)
            expect(
                protected_results
                == [scenario["expected_protected"]]
                * (int(scenario["descendant_depth"]) + 1),
                f"protected descendant attempt escaped for {scenario['id']}",
            )
            expect(
                snapshot_tree(original) == original_before,
                f"protected attempt changed original state for {scenario['id']}",
            )
            protected.cleanup()
            expect(not protected.root.exists(), f"cleanup failed for {scenario['id']}")
            expect(
                snapshot_tree(original) == original_before,
                f"cleanup changed original state for {scenario['id']}",
            )

            weakened = SyntheticBoundary(
                root / f"weakened-{scenario['id']}",
                original,
                weakened=str(scenario["attempt"]),
            )
            weakened_results = attempt_through_descendants(weakened, scenario)
            expect(
                weakened_results
                == [scenario["expected_weakened"]]
                * (int(scenario["descendant_depth"]) + 1),
                f"fixture cannot detect a weakened boundary for {scenario['id']}",
            )
            weakened.cleanup()
            expect(
                snapshot_tree(original) == original_before,
                f"weakened dry run changed original state for {scenario['id']}",
            )

    expected_paths = {
        "tracked-file",
        "untracked-file",
        ".git/index",
        ".git/refs/heads/main",
        ".git/config",
        ".git/hooks/pre-commit",
        ".git/objects/aa/synthetic-object",
    }
    expect(
        set(FIXTURE["preservation_paths"]) == expected_paths,
        "preservation fixture omits tracked, untracked, or Git state",
    )


def reduced_note(raw: bytes, proposed: dict[str, object]) -> tuple[bytes, str]:
    output = FIXTURE["untrusted_output"]
    captured = raw[: int(output["max_capture_bytes"])]
    prohibited = [marker.encode() for marker in output["prohibited_markers"]]
    proposed_text = json.dumps(proposed, sort_keys=True).encode()
    unsafe = any(marker in captured or marker in proposed_text for marker in prohibited)

    if unsafe:
        released = {
            "status": "blocked",
            "exercised_path": "fixture output boundary",
            "observed_result": "untrusted output was withheld",
            "blocked_capabilities": ["safe output release"],
        }
    else:
        released = {
            key: proposed[key]
            for key in (
                "status",
                "exercised_path",
                "observed_result",
                "blocked_capabilities",
            )
        }
    expect(
        released["status"] in {"confirmed", "failed", "insufficient detail", "blocked"},
        "trusted boundary released an unsupported status",
    )
    note = (
        f"{AI_PREFIX}\n\n## Verification\n\n"
        f"**Status:** {released['status']}\n"
        f"**Exercised path:** {released['exercised_path']}\n"
        f"**Observed result:** {released['observed_result']}\n"
        f"**Blocked capabilities:** {', '.join(released['blocked_capabilities'])}\n"
    )
    return captured, note


def check_bounded_sanitized_output() -> None:
    output = FIXTURE["untrusted_output"]
    raw = "\n".join(output["raw_chunks"]).encode()
    expect(
        len(raw) > output["max_capture_bytes"],
        "output fixture does not exercise its byte bound",
    )

    proposed = dict(output["sanitized_result"])
    proposed["unexpected_raw_output"] = raw.decode()
    captured, note = reduced_note(raw, proposed)
    expect(
        len(captured) == output["max_capture_bytes"],
        "trusted fixture boundary did not bound raw output",
    )
    expect("**Status:** blocked" in note, "unsafe raw output did not affect release")
    for marker in output["prohibited_markers"]:
        expect(marker not in note, f"untrusted output reached durable note: {marker}")

    _, safe_note = reduced_note(b"synthetic safe observation", output["sanitized_result"])
    expect("**Status:** failed" in safe_note, "safe reduced result was not released")
    expect(
        "unexpected_raw_output" not in safe_note,
        "unexpected output field reached durable note",
    )
    expect(safe_note.startswith(AI_PREFIX), "durable note lost the AI prefix")

    for phrase in (
        "use the model itself as the sanitizer",
        "credential locations",
        "vault or secret identifiers",
        "private host paths",
        "prompt-like instructions",
    ):
        expect(phrase in SAFE_VERIFICATION, f"output contract omits {phrase!r}")


def check_approval_and_override_dry_runs() -> None:
    plans = FIXTURE["mutation_plans"]
    results: dict[str, bool] = {}
    for case in FIXTURE["approval_dry_runs"]:
        tracker_state = {"labels": [], "comments": [], "closed": False}
        if case["quick_override"]:
            may_mutate = (
                case["maintainer_approved"]
                and case["category_present"]
                and case["plan_listed"]
            )
            external_execution_authorized = False
        else:
            approved_snapshot = (
                case["approved_evidence"],
                case["approved_recommendation"],
                case["approved_plan"],
            )
            current_snapshot = (
                case["current_evidence"],
                case["current_recommendation"],
                case["current_plan"],
            )
            may_mutate = (
                case["maintainer_approved"]
                and case["verification_complete"]
                and case["required_decisions_resolved"]
                and approved_snapshot == current_snapshot
            )
            external_execution_authorized = case["safe_execution_established"]

        if may_mutate:
            plan = plans[case["current_plan"]]
            tracker_state = {
                "labels": plan["labels"],
                "comments": plan["comments"],
                "closed": plan["closed"],
            }

        expect(
            may_mutate == case["expected_mutation"],
            f"wrong approval result for {case['id']}",
        )
        expect(
            external_execution_authorized == case["expected_external_execution"],
            f"quick override or isolation decision authorized unsafe execution for {case['id']}",
        )
        if not may_mutate:
            expect(
                tracker_state == {"labels": [], "comments": [], "closed": False},
                f"unapproved dry run mutated tracker state for {case['id']}",
            )
        for comment in tracker_state["comments"]:
            expect(
                comment.startswith(AI_PREFIX),
                f"dry-run comment lost AI prefix for {case['id']}",
            )
        results[str(case["id"])] = bool(case["expected_mutation"])

    expect(
        not results["missing-maintainer-approval"],
        "normal flow can mutate without explicit maintainer approval",
    )
    expect(results["final-approval"], "final approval cannot apply its outcome")
    expect(not results["changed-evidence"], "changed evidence reused stale approval")
    expect(results["renewed-evidence-approval"], "renewed evidence cannot mutate")
    expect(
        not results["changed-recommendation"],
        "changed recommendation reused stale approval",
    )
    expect(
        results["renewed-recommendation-approval"],
        "renewed recommendation cannot mutate",
    )
    expect(results["quick-override"], "explicit quick override was not preserved")
    expect(
        "without normal verification or grilling" in TRIAGE,
        "quick override does not document its normal-flow bypass",
    )
    expect(
        "A quick override never authorizes execution of external material" in TRIAGE,
        "quick override can authorize unsafe external execution",
    )


def check_contract_language() -> None:
    for phrase in (
        "entire process tree",
        "SSH or GPG agent sockets",
        "private home files",
        "original tracked files, untracked files, index",
        "refs, config, hooks, objects",
        "deny network by default",
        "where the model and public surfaces cannot read them",
        "do not execute. Record verification as `blocked`",
    ):
        expect(phrase in SAFE_VERIFICATION, f"safe-verification omits {phrase!r}")


def main() -> None:
    check_normal_flow_order_and_text()
    check_isolation_decisions()
    check_malicious_fixture_attempts_and_preservation()
    check_bounded_sanitized_output()
    check_approval_and_override_dry_runs()
    check_contract_language()
    print("triage safety tests ok")


if __name__ == "__main__":
    main()
